### ISSUE TITLE
Support for multiple artifacts in a single repo

### ISSUE THREAD

**Issue by bbaldino** [jerus-org/nextsv#209]
Wondering if it's possible to support the idea of multiple artifacts within a single repo, which I think would mainly involve only analyzing commits that affect a specific directory when calculating a new version number.

I did try running `nextsv` from within that directory, but it expects to be able to find the `.git` directory in the directory it's run from, looks like.

**Comment by jerusdp** [comment]
My understanding of the request is:
To maintain individual version numbers for packages within a workspace which would require a tag unique to the package and the source directory for the package.

**Comment by bbaldino** [comment]
Yes I think that's accurate.

**Comment by jerusdp** [comment]
@bbaldino  on branch `subdir-filter`  the following has been implemented for calculate command:

- prefix option to specify a custom prefix to identify the current version number
- subdir option to specify a sub string from the file path that identifies the subset of commits to consider

Can you check if this meets your requirements?

**Comment by jerusdp** [comment]
Released as version 0.10.0
